version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"

  mesos-master:
    image: mesosphere/mesos-master:1.6.2
    container_name: mesos-master
    hostname: mesos-master
    command: --ip=0.0.0.0 --work_dir=/var/lib/mesos
    environment:
      - SWARM_MESOS_USER=root
      - MESOS_SWITCH_USER=0
    ports:
      - "5050:5050"

  mesos-agent1:
    image: mesosphere/mesos-slave:1.6.2
    container_name: mesos-agent1
    hostname: mesos-agent1
    command: --master=mesos-master:5050 --work_dir=/var/lib/mesos --no-switch_user
    links:
      - mesos-master
    environment:
      - MESOS_PORT=5051
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
      - MESOS_LOG_DIR=/var/log/mesos/slave
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
      - MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD=90secs
      - MESOS_DOCKER_STOP_TIMEOUT=60secs
      - MESOS_WORK_DIR=/tmp
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5051:5051"

  mesos-agent2:
    image: mesosphere/mesos-slave:1.6.2
    container_name: mesos-agent2
    hostname: mesos-agent2
    command: --master=mesos-master:5050 --work_dir=/var/lib/mesos --no-switch_user
    links:
      - mesos-master
    environment:
      - MESOS_PORT=5052
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
      - MESOS_LOG_DIR=/var/log/mesos/slave
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
      - MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD=90secs
      - MESOS_DOCKER_STOP_TIMEOUT=60secs
      - MESOS_WORK_DIR=/tmp
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5052:5052"

  marathon:
    image: mesosphere/marathon:v1.6.587
    container_name: marathon
    hostname: marathon
    command: --master mesos-master:5050 --zk zk://zookeeper:2181/marathon
    depends_on:
      - mesos-master
      - zookeeper
    ports:
      - "8080:8080"
    links:
      - mesos-master
      - zookeeper
